# 컬럼명 한글명으로 변환
### - 샘플 trfcard(0) 폴더에 있는 파일을 기준으로 1개만 우선 변환해 보세요

In [11]:
import pandas as pd

In [12]:
df_trf = pd.read_csv('./02_data_통합본/trfcard (0)/trfcard.csv', sep=",")
df_trf_col = pd.read_excel('./02_data_통합본/trfcard (0)/trfcard_columns.xlsx', header=2, usecols = "B, C")

In [13]:
df_trf
df_trf_col
# df_trf_col = df_trf_col.rename(columns=df_trf_col.iloc[0])

       컬럼명 (영문)     컬럼명 (한글)
0       on_date         승차시각
1      off_date         하차시각
2    route_name          노선명
3         descr         노선설명
4      age_type         승객연령
5      trans_yn         환승여부
6     addfee_yn       추가운임여부
7   start_bstop        승차정류장
8   start_gps_x  승차정류장 GPS X
9   start_gps_y  승차정류장 GPS Y
10    end_bstop        하차정류장
11    end_gps_x  하차정류장 GPS X
12    end_gps_y  하차정류장 GPS Y

In [14]:
col_kor = dict()

for nm in df_trf_col.to_dict("records"):
    col_kor[nm['컬럼명 (영문)']] = nm['컬럼명 (한글)']

In [15]:
col_kor

{'on_date': '승차시각',
 'off_date': '하차시각',
 'route_name': '노선명',
 'descr': '노선설명',
 'age_type': '승객연령',
 'trans_yn': '환승여부',
 'addfee_yn': '추가운임여부',
 'start_bstop': '승차정류장',
 'start_gps_x': '승차정류장 GPS X',
 'start_gps_y': '승차정류장 GPS Y',
 'end_bstop': '하차정류장',
 'end_gps_x': '하차정류장 GPS X',
 'end_gps_y': '하차정류장 GPS Y'}

In [65]:
# df.rename(columns = {'old_nm' : 'new_nm'}, inplace = True)
# 딕셔너리 형식을 요구함
df_trf = df_trf.rename(columns = col_kor)
df_trf.head(1)

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675

In [16]:
df_trf_col['컬럼명 (한글)']

0            승차시각
1            하차시각
2             노선명
3            노선설명
4            승객연령
5            환승여부
6          추가운임여부
7           승차정류장
8     승차정류장 GPS X
9     승차정류장 GPS Y
10          하차정류장
11    하차정류장 GPS X
12    하차정류장 GPS Y
Name: 컬럼명 (한글), dtype: object

In [26]:
# col_kor = dict()

# for nm in df_trf_col.to_dict("records"):
#     col_kor[nm['컬럼명 (영문)']] = nm['컬럼명 (한글)']
###### 앞에서 선언함 이미#####

df_trf_new = pd.DataFrame()

for n in range(0,100):
#     print('./02_data_통합본/trfcard ({})/trfcard.csv'.format(n), sep=",")
    df_trf = pd.read_csv(f'./02_data_통합본/trfcard ({n})/trfcard.csv', sep=",")
    df_trf = df_trf.rename(columns = col_kor)
    df_trf_new = pd.concat([df_trf_new,df_trf])
df_trf_new.reset_index(drop = True)

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
1,20200327051514,20200327054956,175,문덕-고속터미널-선린병원-달전,일반,N,N,준양주택3차,129.403063,35.960871,오거리,129.366312,36.031816
2,20200327052343,20200327054659,200,양덕-남구청(야구장)-구룡포,일반,N,N,두호동주민센터,129.378910,36.060370,남구보건소,129.396855,35.992624
3,20200327052449,20200327055412,100,문덕-흥해-신광,일반,N,N,천마아파트,129.409928,35.949403,홈플러스,129.364640,36.030950
4,20200327052848,20200327055231,175,문덕-고속터미널-선린병원-달전,일반,N,N,오천농협세계지점,129.415970,35.967450,죽도시장,129.365169,36.035704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057867,20200122233448,20200122234519,109,양덕-시외터미널-위덕대(유강),일반,Y,N,창포사거리,129.370823,36.061992,삼구4차,129.392204,36.089197
1057868,20200122233905,20200122234736,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,Y,N,오거리,129.366210,36.031340,문화예술회관,129.365551,36.010599
1057869,20200122233907,20200122234057,131,양덕-송도-시청-양학-양덕,일반,N,N,롯데백화점,129.370250,36.050280,영일대 해수욕장,129.376335,36.054052
1057870,20200122234254,20200122234954,200,양덕-남구청(야구장)-구룡포,일반,N,N,죽도파출소,129.362644,36.028456,롯데아파트,129.377403,36.056943
1057871,20200122234302,20200122234544,160,문덕-대송-송도-죽도-용흥,일반,Y,N,대송파출소,129.363570,35.986050,송동,129.362080,35.969720

In [29]:
df_trf_new

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200327051412,20200327051714,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
1,20200327051514,20200327054956,175,문덕-고속터미널-선린병원-달전,일반,N,N,준양주택3차,129.403063,35.960871,오거리,129.366312,36.031816
2,20200327052343,20200327054659,200,양덕-남구청(야구장)-구룡포,일반,N,N,두호동주민센터,129.378910,36.060370,남구보건소,129.396855,35.992624
3,20200327052449,20200327055412,100,문덕-흥해-신광,일반,N,N,천마아파트,129.409928,35.949403,홈플러스,129.364640,36.030950
4,20200327052848,20200327055231,175,문덕-고속터미널-선린병원-달전,일반,N,N,오천농협세계지점,129.415970,35.967450,죽도시장,129.365169,36.035704
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17242,20200122233448,20200122234519,109,양덕-시외터미널-위덕대(유강),일반,Y,N,창포사거리,129.370823,36.061992,삼구4차,129.392204,36.089197
17243,20200122233905,20200122234736,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,Y,N,오거리,129.366210,36.031340,문화예술회관,129.365551,36.010599
17244,20200122233907,20200122234057,131,양덕-송도-시청-양학-양덕,일반,N,N,롯데백화점,129.370250,36.050280,영일대 해수욕장,129.376335,36.054052
17245,20200122234254,20200122234954,200,양덕-남구청(야구장)-구룡포,일반,N,N,죽도파출소,129.362644,36.028456,롯데아파트,129.377403,36.056943
17246,20200122234302,20200122234544,160,문덕-대송-송도-죽도-용흥,일반,Y,N,대송파출소,129.363570,35.986050,송동,129.362080,35.969720

In [32]:
# 등교 및 출근시간인 7시부터 8시 반 사이에 어디서 가장 많이 승차하는가?
df = df_trf_new[['승차시각', '승차정류장']]

In [44]:
df['승차시간'] = df_trf_new['승차시각'].astype(str).str[8:12]

C:\Users\admin\AppData\Local\Temp/ipykernel_12024/2683817539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['승차시간'] = df_trf_new['승차시각'].astype(str).str[8:12]

In [49]:
df_1 = df[(df_trf_new['승차시각'].astype(str).str[8:12].astype(int) > 700) &\
(df_trf_new['승차시각'].astype(str).str[8:12].astype(int) < 830)].reset_index(drop=True)

                 승차시각     승차정류장  승차시간
0      20200327070100    GS슈퍼마켓  0701
1      20200327070230      교보생명  0702
2      20200327070302  현진에버빌3단지  0703
3      20200327070319     초곡리종점  0703
4      20200327070321     용덕사거리  0703
...               ...       ...   ...
87238  20200122082944    노인복지회관  0829
87239  20200122082946      환호여중  0829
87240  20200122082949  해군 항공역사관  0829
87241  20200122082952  해군 항공역사관  0829
87242  20200122082955      교보생명  0829

[87243 rows x 3 columns]

In [75]:
# 15분 단위로 자르기
for i in range(len(df_1)):
    if int(df_1['승차시간'][i]) <= 715:
        df_test['승차시간'][i] = '0700'

C:\Users\admin\AppData\Local\Temp/ipykernel_12024/2633125450.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['승차시간'][i] = '0700'

In [54]:
for i in range(len(df_1)):
    if df_test['승차시간'][i].astype(int) < 715:

'0701'

In [74]:
df_test = df_1